export const resources = [
    {
        link: 'https://www.youtube.com/watch?v=Trg8IjdXaPo',
        title: 'Simple Man Guitar Lesson for Beginners - Easy Easy Easy',
        description: 'ok description here is a description ok description here is a description ok description here is a description ok description here is a description ok description here is a description ok description here is a description',
        tags: ['new', 'guitar', 'tutorial'],
        category: 'instruments',
        childCategory: 'guitar',
        grandChildCategory: '',
        greatGrandChildCategory: '',
        id: 1,
    },
    {
        link: 'https://www.youtube.com/watch?v=WGIcfDCWysQ',
        title: '2nd tutorial',
        description: 'ok description here is a description ok description here is a description ok description here is a description ok description here is a description ok description here is a description ok description here is a description 2',
        tags: ['brand new', 'guitar', 'tutorial'],
        category: 'instruments',
        childCategory: 'guitar',
        grandChildCategory: '',
        greatGrandChildCategory: '',
        id: 2,
    },
    {
        link: 'https://www.youtube.com/watch?v=sf-RI1YPvqY',
        title: 'faster fingers',
        description: 'ok description here is a description ok description here is a description ok description here is a description ok description here is a description ok description here is a description ok description here is a description 3',
        tags: ['bass', 'guitar', 'tutorial'],
        category: 'instruments',
        childCategory: 'bass',
        grandChildCategory: '',
        greatGrandChildCategory: '',
        id: 3,
    },
];